webapp:
  hosts:
    web1:
      ansible_host: localhost
      ansible_port: 2022
      ansible_ssh_user: root
      ansible_ssh_pass: root
      # ansible_ssh_private_key_file: ~/.ssh/isucon
      ansible_python_interpreter: /usr/bin/python3
