- name: Create dir
  file:
    path: '{{ alp_work_dir }}'
    state: directory

- name: Download binary
  get_url:
    url: "https://github.com/tkuchiki/alp/releases/download/{{ alp_version }}/alp_linux_amd64.zip"
    dest: "{{ alp_work_dir }}/alp_linux_amd64.zip"
  register: result
  until: result is succeeded
  retries: 3
  delay: 5

- name: Install unzip command with yum
  yum:
    name: unzip
  when: ansible_os_family == 'RedHat'

- name: Install unzip command with apt-get
  apt:
    name: unzip
  when: ansible_os_family == 'Debian'

- name: Unzip package
  unarchive:
    src: '{{ alp_work_dir }}/alp_linux_amd64.zip'
    dest: '{{ alp_work_dir }}'
    remote_src: yes

- name: Put binary in /usr/local/bin/
  copy:
    src: '{{ alp_work_dir }}/alp'
    dest: '{{ alp_install_loc }}/'
    remote_src: yes

- name: chmod a+x
  file:
    dest: '{{ alp_install_loc }}/alp'
    mode: a+x

